feat/x86_64
Start9Labs/spark-wallet-wrapper pull request #20
Opened 2022-10-12 22:05 UTC by gStart9

2022-10-12 22:06 UTC, gStart9 commented
Also added a version bump in there

2022-10-28 19:17 UTC, elvece commented on Makefile
> +	DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build --tag start9/$(PKG_ID)/main:$(PKG_VERSION) --platform=linux/arm64 -o type=docker,dest=docker-images/aarch64.tar .
```suggestion
	DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build --tag start9/$(PKG_ID)/main:$(PKG_VERSION) --platform=linux/arm64 --build-arg PLATFORM=arm64 -o type=docker,dest=docker-images/aarch64.tar .
```

2022-10-28 19:17 UTC, elvece commented on Makefile
> +	DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build --tag start9/$(PKG_ID)/main:$(PKG_VERSION) --platform=linux/amd64 -o type=docker,dest=docker-images/x86_64.tar .
```suggestion
	DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build --tag start9/$(PKG_ID)/main:$(PKG_VERSION) --platform=linux/amd64 --build-arg ARCH=x86_64 --build-arg PLATFORM=amd64 -o type=docker,dest=docker-images/x86_64.tar .
```

2022-10-28 19:19 UTC, elvece commented on Dockerfile
> +ARG ARCH
```suggestion
```

does not seem like this is actually needed in your Dockerfile, just the `PLATFORM`

2022-12-12 18:25 UTC, elvece approved these changes

2022-12-12 18:26 UTC, elvece commented
Needs rebase and rename to reflect actual change, which is converting main procedure to JS.

2022-12-12 18:27 UTC, elvece requested changes
Needs rebase and rename to reflect actual change, which is converting main procedure to JS.

2022-12-12 18:40 UTC, closed without merging